addons:
  code_climate:
    repo_token: 5e4cc9cbe37fd93fab17d38985da932c6ee2b73bcc58e0dd63f54be8e4aee921
language: ruby
before_install:
  - gem update --system
  - gem update bundler
env:
  global:
    secure: P5IpEGYYbF0HcP9Mj9/zZAUXpUjkA2YkGLClvbVGsOD5zI9Jj1RZAlCC/fBKtfPUlfjlADp1hIN++n7qnqqmXPw4X/BC2V8Ios91NoFQeKfjQENSmjYykFTCp1CkBmCjq+lb/yE/JPQnVOoI/eEm5uaNSRc/XLjHwuSdKEFPv8M=
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2.0
  - 2.3.0
  - jruby-18mode
  - jruby-19mode
  - ruby-head
  - jruby-head
  - ree
matrix:
  allow_failures:
    - rvm: 1.8.7
    - rvm: 1.9.2
    - rvm: 1.9.3
    - rvm: ree
    - rvm: jruby-18mode
    - rvm: jruby-19mode
    - rvm: jruby-head
    - rvm: ruby-head
  fast_finish: true
